Samplenet/Controllers/CartController.cs
using RestaurantReservation.BL.Entities;
using RestaurantReservation.BL.Repositories;
using RestaurantReservation.WebUI.ViewModels;
using System.Web.Mvc;

namespace RestaurantReservation.WebUI.Controllers
{
    public class CartController : Controller
    {
        private IDishRepository dishRepository;

        public CartController()
        {

        }

        public CartController(IDishRepository repository)
        {
            this.dishRepository = repository;
        }

        public ActionResult Index()
        {
            Cart cart = Cart.GetCart();

            DishIndexViewModel viewModel = new DishIndexViewModel
            {
                Cart = cart,
                CartLines = cart.GetCartLines(),

            };
            return View(viewModel);
        }

        public ActionResult AddToCart(int dishId)
        {
            Cart cart = Cart.GetCart();



            cart.AddItem(dishId, table: 1, size: DishSize.Standard);

            return RedirectToAction("Index");

        }



        public ActionResult RemoveLine(int id)
        {
            Cart cart = Cart.GetCart();
            cart.RemoveLine(dishRepository.GetDishbyId(id));
            return RedirectToAction("Index");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult UpdateCart(DishIndexViewModel viewModel)
        {
            Cart cart = Cart.GetCart();

            cart.Update(viewModel.CartLines);
            return RedirectToAction("Index");
        }



        public PartialViewResult CartSummary()
        {
            Cart cart = Cart.GetCart();
            CartSummaryViewModel viewModel = new CartSummaryViewModel
            {
                NumberOfDishes = cart.GetNumberOfDish(),
                TotalCost = cart.ComputeTotalValue()
            };
            return PartialView(viewModel);
        }



    }
}

Samplenet/Controllers/DishController.cs
using RestaurantReservation.BL.Repositories;
using RestaurantReservation.WebUI.ViewModels;
using System;
using System.Linq;
using System.Web.Mvc;

namespace RestaurantReservation.WebUI.Controllers
{
    public class DishController : Controller
    {
        private IDishRepository dishRepository;
        private ICategoryRepository categoryRepository;

        public DishController()
        {

        }

        public DishController(IDishRepository repository, ICategoryRepository categoryRepository)
        {
            this.dishRepository = repository;
            this.categoryRepository = categoryRepository;
        }

        public ViewResult List(string category)
        {

            DishCatalogueViewModel viewModel = new DishCatalogueViewModel();
            if (String.IsNullOrEmpty(category))
            {
                viewModel.Dishes = dishRepository.Dishes.ToList();
                viewModel.CurrentCattegory = "All Dishes";

            }
            else
            {
                viewModel.Dishes = dishRepository.GetDishesbyCategory(category);
                viewModel.CurrentCattegory = category;

            }
            return View(viewModel);
        }

        public ViewResult Detail(int id)
        {
            var dish = dishRepository.GetDishbyId(id);
            return View(dish);
        }






    }
}

Samplenet/Controllers/OrderController.cs
using RestaurantReservation.BL.Repositories;
using System.Web.Mvc;

namespace RestaurantReservation.WebUI.Controllers
{

    public class OrderController : Controller
    {
        private IOrderRepository orderRepository;
        private IOrderLineRepository orderLineRepository;
        private IServeListRepository serveRepository;

        public OrderController(IOrderRepository repository, IOrderLineRepository lineRepository, IServeListRepository serveRepository)
        {
            this.orderRepository = repository;
            this.orderLineRepository = lineRepository;
            this.serveRepository = serveRepository;

        }
        // GET: Order

        [Authorize(Roles = "Admin,Owner")]
        public ActionResult Index()
        {
            var pendingServeLists = serveRepository.GetPendingServeLists();
            return View(pendingServeLists);
        }


        [Authorize(Roles = "Admin,Owner")]
        public ActionResult OrderList()
        {
            var orderLists = orderRepository.Orders;
            return View(orderLists);
        }

        [Authorize(Roles = "Admin,Owner")]
        public ActionResult OrderDetails(int id)
        {
            var order = orderRepository.GetOrderById(id);
            return View(order);

        }

        [Authorize]
        public ActionResult CustomerOrder(string userId)
        {
            var orders = orderRepository.GetOrderByUserId(userId);
            return View(orders);

        }
    }
}

Samplenet/Views/Shared/DishSummary.cshtml
@model RestaurantReservation.BL.Entities.Dish
@using RestaurantReservation.WebUI.Constant

<div class="col-sm-4 col-lg-4 col-md-4 text-center dishTileTray">
    <div class="dishTile">
        <div>
            <img class="dishThumbnail" src="@(Url.Content(Constant.DishImagePath) +
                        @Model.DishImageMappings.OrderBy(pim =>
                        pim.ImageNumber).ElementAt(0).DishImage.FileName)">

        </div>
        <div class="detail">
            <h3>
                <strong><a class="dishLink" href="@Url.Action("Detail","Dish",new { id = Model.DishID })">@Model.Name</a></strong>
               
               
            </h3>
            <h4>@Model.StandardPrice</h4>
        </div>
        @using (Html.BeginForm("AddToCart", "Cart", new { id = Model.DishID }))
        {
            <div>
                @Html.HiddenFor(m => m.DishID)
                @Html.Hidden("returnUrl", Request.Url.PathAndQuery)
                <input type="submit" class="btn addCart" value="Add to cart" />
            </div>
        }
    </div>
   
</div>
            
                

Samplenet/Views/Shared/_AdminLayout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("DelightRestaurant", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Menu", "List", "Dish")</li>
                 
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
   
    <div class="container body-content">
        <div class="col-md-2 adminButtonColumn">
            @Html.Action("AdminButton", "Admin")
        </div>
        <div class="col-md-10">
            @RenderBody()
        </div>
       

        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

Samplenet/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Delight Restaurant", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Menu", "List", "Dish")</li>
                    <li><a href="@Url.Action("CustomerOrder","Order",new { userId = User.Identity.Name })">Your Order</a></li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        
        <div>
            @RenderBody()
        </div>
       
       
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>