Samplenet/Controllers/DishImageController.cs
using RestaurantReservation.BL.Entities;
using RestaurantReservation.BL.Repositories;
using System.Linq;
using System.Web;
using System.Web.Helpers;
using System.Web.Mvc;

namespace RestaurantReservation.WebUI.Controllers
{
    public class DishImageController : Controller
    {
        private IDishImageRepository imageRepository;

        public DishImageController()
        {

        }

        public DishImageController(IDishImageRepository repository)
        {
            this.imageRepository = repository;
        }

        public ActionResult Upload()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Upload(HttpPostedFileBase[] files)
        {
            bool allValid = true;
            string inValidFiles = "";

            if (files[0] != null)
            {

                if (files.Length <= 4)
                {

                    foreach (var file in files)
                    {
                        if (!ValidateFile(file))
                        {
                            allValid = false;
                            inValidFiles += ", " + file.FileName;
                        }
                    }

                    if (allValid)
                    {
                        foreach (var file in files)
                        {
                            try
                            {
                                SaveFileToDisk(file);
                            }
                            catch (System.Exception)
                            {
                                ModelState.AddModelError("FileName", "Sorry an error occurred saving the files to disk, please try again");
                            }
                        }
                    }
                    //else add an error listing out the invalid files            
                    else
                    {
                        ModelState.AddModelError("FileName", "All files must be gif, png, jpeg or jpg  and less than 2MB in size.The following files" + inValidFiles +
                            " are not valid");
                    }
                }
                //the user has entered more than 10 files
                else
                {
                    ModelState.AddModelError("FileName", "Please only upload up to ten files at a time");
                }
            }
            else
            {
                //if the user has not entered a file return an error message
                ModelState.AddModelError("FileName", "Please choose a file");
            }

            if (ModelState.IsValid)
            {
                bool duplicates = false;
                bool otherDbError = false;
                string duplicateFiles = "";
                foreach (var file in files)
                {
                    //try and save each file
                    var image = new DishImage { FileName = file.FileName };


                    imageRepository.SaveImage(image);

                    //if there is an exception check if it is caused by a duplicate file

                }
                //add a list of duplicate files to the error message
                if (duplicates)
                {
                    ModelState.AddModelError("FileName", "All files uploaded except the files" + duplicateFiles + ", which already exist in the system." +
                        " Please delete them and try again if you wish to re-add them");
                    return View();
                }
                else if (otherDbError)
                {
                    ModelState.AddModelError("FileName", "Sorry an error has occurred saving to the database, please try again");
                    return View();
                }
                return RedirectToAction("Index");
            }
            return View();
        }

        private bool ValidateFile(HttpPostedFileBase file)
        {
            string fileExtension = System.IO.Path.GetExtension(file.FileName).ToLower();
            string[] allowedFileTypes = { ".gif", ".png", ".jpeg", ".jpg" };
            if ((file.ContentLength > 0 && file.ContentLength < 2097152) && allowedFileTypes.Contains(fileExtension))
            {
                return true;
            }
            return false;
        }

        private void SaveFileToDisk(HttpPostedFileBase file)
        {
            WebImage img = new WebImage(file.InputStream);
            if (img.Width != 200 || img.Height != 150)
            {
                img.Resize(200, 150);
            }
            img.Save(Constant.Constant.DishImagePath + file.FileName);
            if (img.Width > 100)
            {
                img.Resize(100, img.Height);
            }
            img.Save(Constant.Constant.DishThumbnailPath + file.FileName);
        }
    }
}

Samplenet/Controllers/OrderController.cs
using RestaurantReservation.BL.Repositories;
using System.Web.Mvc;

namespace RestaurantReservation.WebUI.Controllers
{

    public class OrderController : Controller
    {
        private IOrderRepository orderRepository;
        private IOrderLineRepository orderLineRepository;
        private IServeListRepository serveRepository;

        public OrderController(IOrderRepository repository, IOrderLineRepository lineRepository, IServeListRepository serveRepository)
        {
            this.orderRepository = repository;
            this.orderLineRepository = lineRepository;
            this.serveRepository = serveRepository;

        }
        // GET: Order

        [Authorize(Roles = "Admin,Owner")]
        public ActionResult Index()
        {
            var pendingServeLists = serveRepository.GetPendingServeLists();
            return View(pendingServeLists);
        }


        [Authorize(Roles = "Admin,Owner")]
        public ActionResult OrderList()
        {
            var orderLists = orderRepository.Orders;
            return View(orderLists);
        }

        [Authorize(Roles = "Admin,Owner")]
        public ActionResult OrderDetails(int id)
        {
            var order = orderRepository.GetOrderById(id);
            return View(order);

        }

        [Authorize]
        public ActionResult CustomerOrder(string userId)
        {
            var orders = orderRepository.GetOrderByUserId(userId);
            return View(orders);

        }
    }
}

Samplenet/Controllers/RoleController.cs
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.EntityFramework;
using Microsoft.AspNet.Identity.Owin;
using RestaurantReservation.BL.Entities;
using RestaurantReservation.WebUI.ViewModels.Admin;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace RestaurantReservation.WebUI.Controllers
{
    [Authorize(Roles = "Owner")]
    public class RoleController : Controller
    {
        public RoleController()
        {

        }

        public RoleController(ApplicationUserManager userManager, ApplicationRoleManager roleManager)
        {
            UserManager = userManager;
            RoleManager = roleManager;

        }

        private ApplicationUserManager _userManager;
        public ApplicationUserManager UserManager
        {
            get
            {
                return _userManager ??
                   HttpContext.GetOwinContext().GetUserManager<ApplicationUserManager>();
            }
            set
            {
                _userManager = value;
            }
        }
        private ApplicationRoleManager _roleManager;
        public ApplicationRoleManager RoleManager
        {
            get
            {
                return _roleManager ?? HttpContext.GetOwinContext().Get<ApplicationRoleManager>();
            }
            private set
            {
                _roleManager = value;
            }
        }

        // GET: Role
        public ActionResult Index()
        {

            return View(RoleManager.Roles);
        }



        // GET: Role/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Role/Create
        [HttpPost]
        public async Task<ActionResult> Create(RoleViewModel roleViewModel)
        {
            if (ModelState.IsValid)
            {
                var role = new IdentityRole(roleViewModel.Name);
                var roleresult = await RoleManager.CreateAsync(role);
                if (!roleresult.Succeeded)
                {
                    ModelState.AddModelError("", roleresult.Errors.First());
                    return View();
                }
                return RedirectToAction("Index");
            }
            return View();
        }


        // GET: Role/Edit/5
        public async Task<ActionResult> Edit(string id)
        {

            var role = await RoleManager.FindByIdAsync(id);
            if (role == null)
            {
                return HttpNotFound();
            }
            RoleViewModel roleModel = new RoleViewModel { Id = role.Id, Name = role.Name };
            return View(roleModel);
        }


        // POST: Role/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit(RoleViewModel roleModel)
        {
            if (ModelState.IsValid)
            {
                var role = await RoleManager.FindByIdAsync(roleModel.Id);
                role.Name = roleModel.Name;
                await RoleManager.UpdateAsync(role);
                return RedirectToAction("Index");
            }
            return View();
        }


        // GET: Role/Details/string
        public async Task<ActionResult> Details(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var role = await RoleManager.FindByIdAsync(id);
            // Get the list of Users in this Role
            var users = new List<ApplicationUser>();
            // Get the list of Users in this Role
            foreach (var user in UserManager.Users.ToList())
            {
                if (await UserManager.IsInRoleAsync(user.Id, role.Name))
                {
                    users.Add(user);
                }
            }
            ViewBag.Users = users;
            ViewBag.UserCount = users.Count();
            return View(role);
        }

        //GET: Role/Delete/string
        public async Task<ActionResult> Delete(string id)
        {

            var role = await RoleManager.FindByIdAsync(id);
            if (role == null)
            {
                return HttpNotFound();
            }
            return View(role);
        }


        // POST: Role/Delete/string
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(string id)
        {
            if (ModelState.IsValid)
            {

                var role = await RoleManager.FindByIdAsync(id);
                if (role == null)
                {
                    return HttpNotFound();
                }
                IdentityResult result = await RoleManager.DeleteAsync(role);
                if (!result.Succeeded)
                {
                    ModelState.AddModelError("", result.Errors.First());
                    return View();
                }
                return RedirectToAction("Index");
            }
            return View();
        }

    }
}

Samplenet/Controllers/UserController.cs
using Microsoft.AspNet.Identity.Owin;
using RestaurantReservation.BL.Entities;
using RestaurantReservation.WebUI.ViewModels;
using RestaurantReservation.WebUI.ViewModels.Admin;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace RestaurantReservation.WebUI.Controllers
{
    [Authorize(Roles = "Owner")]
    public class UserController : Controller
    {
        public UserController()
        {

        }

        public UserController(ApplicationRoleManager roleManager, ApplicationUserManager userManager)
        {
            RoleManager = roleManager;
            UserManager = userManager;
        }

        private ApplicationUserManager _userManager;
        public ApplicationUserManager UserManager
        {
            get
            {
                return _userManager ??
                   HttpContext.GetOwinContext().GetUserManager<ApplicationUserManager>();
            }
            private set
            {
                _userManager = value;
            }
        }
        private ApplicationRoleManager _roleManager;
        public ApplicationRoleManager RoleManager
        {
            get
            {
                return _roleManager ?? HttpContext.GetOwinContext().Get<ApplicationRoleManager>();
            }
            private set
            {
                _roleManager = value;
            }
        }

        // GET: User
        public async Task<ActionResult> Index()
        {
            return View(await UserManager.Users.ToListAsync());
        }




        // GET: User/Create
        public async Task<ActionResult> Create()
        {
            //Get the list of Roles
            ViewBag.RoleId = new SelectList(await RoleManager.Roles.ToListAsync(), "Name", "Name");
            return View();
        }


        // POST: User/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create(RegisterViewModel viewModel, params string[]
     selectedRoles)
        {
            if (ModelState.IsValid)
            {
                var user = new ApplicationUser
                {
                    UserName = viewModel.Email,
                    Email = viewModel.Email,

                };
                var adminresult = await UserManager.CreateAsync(user, viewModel.Password);
                //Add User to the selected Roles
                if (adminresult.Succeeded)
                {
                    if (selectedRoles != null)
                    {
                        var result = await UserManager.AddToRolesAsync(user.Id, selectedRoles);
                        if (!result.Succeeded)
                        {
                            ModelState.AddModelError("", result.Errors.First());
                            ViewBag.RoleId = new SelectList(await RoleManager.Roles.ToListAsync(),
                              "Name", "Name");
                            return View();
                        }
                    }
                }
                else
                {
                    ModelState.AddModelError("", adminresult.Errors.First());
                    ViewBag.RoleId = new SelectList(RoleManager.Roles, "Name", "Name");
                    return View();
                }
                return RedirectToAction("Index");
            }
            ViewBag.RoleId = new SelectList(RoleManager.Roles, "Name", "Name");
            return View();
        }


        // GET: User/Edit/string
        public async Task<ActionResult> Edit(string id)
        {
            var user = await UserManager.FindByIdAsync(id);
            if (user == null)
            {
                return HttpNotFound();
            }
            var userRoles = await UserManager.GetRolesAsync(user.Id);
            return View(new UserViewModel()
            {
                Id = user.Id,
                Email = user.Email,

                RolesList = RoleManager.Roles.ToList().Select(x => new SelectListItem()
                {
                    Selected = userRoles.Contains(x.Name),
                    Text = x.Name,
                    Value = x.Name
                })
            });
        }

        // POST: User/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit(UserViewModel viewModel, params string[] selectedRole)
        {
            if (ModelState.IsValid)
            {
                var user = await UserManager.FindByIdAsync(viewModel.Id);


                var userRoles = await UserManager.GetRolesAsync(user.Id);
                selectedRole = selectedRole ?? new string[] { };
                var result = await UserManager.AddToRolesAsync(user.Id,
                    selectedRole.Except(userRoles).ToArray<string>());
                if (!result.Succeeded)
                {
                    ModelState.AddModelError("", result.Errors.First());
                    return View();
                }
                result = await UserManager.RemoveFromRolesAsync(user.Id,
                    userRoles.Except(selectedRole).ToArray<string>());
                if (!result.Succeeded)
                {
                    ModelState.AddModelError("", result.Errors.First());
                    return View();
                }
                return RedirectToAction("Index");
            }
            ModelState.AddModelError("", "Something failed.");
            return View();
        }



    }
}

Samplenet/Views/Admin/AdminButton.cshtml
<div class="pull-left adminButtonTray">
    <a href="@Url.Action("Dish")" class="btn btn-default adminButton">Catalogue</a>
    <a href="@Url.Action("Upload","DishImage")" class="btn btn-default adminButton">Dish Image</a>
    <a href="@Url.Action("Index","Role")" class="btn btn-default adminButton">Manage Roles</a>
    <a href="@Url.Action("Index","User")" class="btn btn-default adminButton">Manage Users</a>
    <a href="@Url.Action("Index","Order")" class="btn btn-default adminButton">Serve List</a>
    <a href="@Url.Action("OrderList","Order")" class="btn btn-default adminButton">Order List</a>

</div>

Samplenet/Views/Admin/Delete.cshtml
@model RestaurantReservation.BL.Entities.Dish

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h2>Are you sure you want to delete @Model.Name</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-actions no-color">
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        @Html.ActionLink("Back to List", "Index")
    </div>
}

Samplenet/Views/Admin/Dish.cshtml
@model IEnumerable<RestaurantReservation.BL.Entities.Dish>

@{
    ViewBag.Title = "Admin : All Dishes";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h2>All Dishes</h2>



<div class="panel panel-default">
    <div class="panel-title">      
        @if (Request.IsAuthenticated && User.IsInRole("Owner"))
        {
            <a href="@Url.Action("Create")" class="btn btn-default adminAddDish"> Add new dish</a>
        }
       
    </div>   
   
    <div class="panel-body">        
        <table class="table table-bordered table-striped"> 
            <thead>
                <tr>
                    <th class="text-right">ID</th>
                    <th class="text-right">Name</th>
                    <th class="text-right">Price</th>
                    <th class="text-right">Actions</th>
                </tr> 
            </thead>
                     
            @foreach (var dish in Model)
            {
                <tr class="text-right">     
                    <td>@dish.DishID</td>                    
                    <td><a href="@Url.Action("Detail","Dish",new{id =dish.DishID})">@dish.Name</a></td>                    
                    <td>@dish.StandardPrice.ToString("c")</td>                    
                    <td>                        
                      <span><a href="@Url.Action("Edit", new {id = dish.DishID})"> Edit </a></span>
                      <span><a href="@Url.Action("Delete", new {id = dish.DishID})"> Delete </a></span>
                    </td>                
                </tr>           
            }        
         </table>    
    </div>    
   
</div>

Samplenet/Views/Admin/DishForm.cshtml
@model RestaurantReservation.WebUI.ViewModels.DishFormViewModel

@{
    ViewBag.Title = "Update";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h2>@Model.Heading</h2>

@using (Html.BeginForm(Model.Action, "Admin"))
{
    <p class="alert alert-info">All fields are <strong>required</strong>.</p>
    @Html.AntiForgeryToken()
    @Html.HiddenFor(d =>d.DishID)
    <div class="form-group">
        @Html.LabelFor(d=>d.Name)
        @Html.TextBoxFor(e => e.Name, new { @class = "form-control", autofocus = "autofocus" })
        @Html.ValidationMessageFor(d=>d.Name)
    </div>
    <div class="form-group">
        @Html.LabelFor(d=>d.StandardPrice)
        @Html.TextBoxFor(d=>d.StandardPrice, new { @class = "form-control"})
        @Html.ValidationMessageFor(d=>d.StandardPrice)
    </div>
    <div class="form-group">
        @Html.LabelFor(d =>d.CategoryID)
        @Html.DropDownListFor(d=>d.CategoryID, Model.CategoryList,new { @class = "form-control" })
        @Html.ValidationMessageFor(e => e.CategoryID)
    </div>
    
    <div class="form-group">
        @Html.LabelFor(d=>d.Description)
        @Html.TextAreaFor(d=>d.Description, new { @class = "form-control" })
        @Html.ValidationMessageFor(d =>d.Description)
    </div>
    for (int i = 0; i < Model.ImageLists.Count; i++)
    {
        <div class="form-group">
            <label>Dish Image @(i + 1):</label>
            <div>
                @Html.DropDownListFor(d => d.DishImages, Model.ImageLists[i], "Choose Image",new { @class = "form-control" })
            
      
            </div>
        </div>
    }
    <div class="form-group">
        <button type="submit" class="btn btn-primary">Save</button>
    </div>
}

@section scripts
{
    @Scripts.Render("~/bundles/jqueryval")
}